#!/bin/sh

apt-get update
apt-get install -y curl
curl -i --data @heat_control/ResourceTopology.json -X POST http://9.1.189.10:8080/topology
curl -i --data @heat_control/Requirements.json -X POST http://9.1.189.10:8080/requirements
